### ISSUE TITLE
UI Events integration

### ISSUE THREAD

**Issue by genjohnson** [uiowa/hr.uiowa.edu#10]
Allow content contributors to add lists of upcoming events to any Basic Page.

**Comment by joewhitsitt** [comment]
There is an initial attempt of [uiowa_events in the rusty repo](https://github.com/uiowa/rusty/tree/uiowa_events) that provides the events page, configurable block, configurable paragraph type. campus has not finalized what uiowa_events in D8 should look like yet.

**Comment by joewhitsitt** [comment]
This is in Rusty now.
