### ISSUE TITLE
Investigate better menu management

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/hr.uiowa.edu#13]
They have a very large menu and default menu management in D8 is limited. Their D7 site currently has the SiteNow implementation of Menu Link Weight, but they still felt the need to mention menu management in a recent meeting.

[Menu Link Weight](https://www.drupal.org/project/menu_link_weight) has a D8 alpha version that relies on several other modules (beta, alpha versions).

**Comment by adamdelaney** [comment]
Closing in favor of https://github.com/uiowa/sitenow/issues/323.
