### ISSUE TITLE
Sidebar menu should use active page rather than hard coded main menu

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/hr.uiowa.edu#20]
Use case would be to show children of a menu item that has been placed in the footer menu.

**Comment by joewhitsitt** [comment]
Will need to create two additional menu blocks for hr since the D8 version of menu block is still without the _"the menu selected by the page"_ feature https://www.drupal.org/project/menu_block/issues/2757143

**Comment by joewhitsitt** [comment]
This is done. Had to create two new menu blocks and place them in HR's sidebar.
