### ISSUE TITLE
Investigate draggable menu not saving properly

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/hr.uiowa.edu#21]
The browser in question was a mac using safari.

**Comment by joewhitsitt** [comment]
Unable to reproduce locally using Mac Chrome/Safari. It is a large menu, we need to make sure Lin knows to scroll all the way to the bottom to save the menu order after the drag/drop.

**Comment by joewhitsitt** [comment]
This was replaicated in Stage and is related to max_input_vars which is currently set at 1000.

**Comment by joewhitsitt** [comment]
Acquia increased the server to 3000 and the problem appears to be fixed... for now.
