### ISSUE TITLE
Investigate icon images cutting off

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/hr.uiowa.edu#24]

**Comment by joewhitsitt** [comment]
Looks like the icon in question is 267x350px so the cutoff occurs.
https://hr-d8.stage.drupal.uiowa.edu/sites/hr.uiowa.edu/files/2019-02/adminservices.gif

Similarily, a square icon in DEV produced even spaced results:
<img width="459" alt="Screen Shot 2019-03-12 at 1 07 24 PM" src="https://user-images.githubusercontent.com/4663676/54224681-01736b00-44c8-11e9-9d28-2458c7ebade7.png">

**Comment by joewhitsitt** [comment]
Going to adjust the image style to not crop. Square images are recommended
