### ISSUE TITLE
Option to move page title off-screen

### ISSUE THREAD

**Issue by genjohnson** [uiowa/hr.uiowa.edu#7]
Per the wire frames for top-level landing pages and possible other landing pages, content contributors should be able to select to have the page title displayed off-screen on Basic Pages.

**Comment by joewhitsitt** [comment]
There is a [PR in rusty](https://github.com/uiowa/rusty/pull/228) to address this. Rusty/HR is currently using the page_title block which this functionality is based off.

**Comment by joewhitsitt** [comment]
This got added to rusty master.
